version: '3.8'
services:
  #---# PHP-FPM #---#
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: WebSistemaJugos_app
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - app-network

  #---# NGINX #---#
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 128m
    container_name: WebSistemaJugos_nginx
    restart: unless-stopped
    ports:
      - "6080:80"
    depends_on:
      - app
    networks:
      - app-network

  #---# MySQL #---#
  db:
    image: mysql:8.0
    deploy:
      resources:
        limits:
          memory: 1g
    container_name: WebSistemaJugos_db
    restart: unless-stopped
    ports:
      - "6306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./merakifruit.sql:/docker-entrypoint-initdb.d/merakifruit.sql
      - ./merakifruit.sql:/docker-entrypoint-initdb.d/merakifruit.sql
    networks:
      - app-network

  #---# Pusher (Soketi) #---#
  pusher:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    deploy:
      resources:
        limits:
          memory: 256m
    container_name: WebSistemaJugos_pusher
    restart: unless-stopped
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      SOKETI_DEBUG: "0"
      SOKETI_APP_ID: ${PUSHER_APP_ID}
      SOKETI_APP_KEY: ${PUSHER_APP_KEY}
      SOKETI_APP_SECRET: ${PUSHER_APP_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local